/**
 * InsureLink Database Seed Script
 * ================================
 * Seeds the Supabase PostgreSQL database with demo data that matches
 * the frontend's hardcoded/JSON data files.
 *
 * UUIDs are auto-generated by Supabase, not custom-generated.
 *
 * Run: npx ts-node prisma/seed.ts
 */

import 'dotenv/config';
import { PrismaClient } from '@prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';
import * as bcrypt from 'bcrypt';

// ---------------------------------------------------------------------------
// Prisma client setup (matches the project's PrismaPg adapter approach)
// ---------------------------------------------------------------------------
const databaseUrl = process.env.DATABASE_URL;
if (!databaseUrl) throw new Error('DATABASE_URL is not set in .env');

const adapter = new PrismaPg({ connectionString: databaseUrl });
const prisma = new PrismaClient({ adapter });

// ---------------------------------------------------------------------------
// Dynamic ID Maps - populated at runtime with auto-generated UUIDs
// ---------------------------------------------------------------------------
const createdIds = {
  insurerUser: '' as string,
  insurer: '' as string,
  corpUsers: [] as string[],
  corps: [] as string[],
  hospUsers: [] as string[],
  hosps: [] as string[],
  empUsers: [] as string[],
  emps: [] as string[],
  plans: [] as string[],
  deps: [] as string[],
  visits: [] as string[],
  claims: [] as string[],
  labs: [] as string[],
  emergContacts: [] as string[],
  notifications: [] as string[],
};

// Map frontend string IDs → runtime UUIDs (populated during seeding)
const ID_MAP: Record<string, string> = {};

// ---------------------------------------------------------------------------
// DATA DEFINITIONS (matching frontend JSON files)
// ---------------------------------------------------------------------------

// ---- EMPLOYEES (from employees.json + patients.json for extra fields) ----
interface EmployeeData {
  id: string;
  employeeNumber: string;
  name: string;
  email: string;
  mobile: string;
  corporateId: string;
  planId: string;
  coverageStart: string;
  coverageEnd: string;
  designation: string;
  department: string;
  // From patients.json
  cnic?: string;
  dob?: string;
  gender?: string;
  address?: string;
}

const employees: EmployeeData[] = [
  {
    id: 'emp-001',
    employeeNumber: 'E-1001',
    name: 'Ali Raza',
    email: 'ali.raza@acme.com',
    mobile: '+92-300-1000001',
    corporateId: 'corp-001',
    planId: 'plan-acme-gold-2025',
    coverageStart: '2025-01-01',
    coverageEnd: '2025-12-31',
    designation: 'Engineer',
    department: 'R&D',
    cnic: '42101-1234567-1',
    dob: '1991-03-15',
    gender: 'Male',
    address: 'House 12, Street 5, F-8/3, Islamabad',
  },
  {
    id: 'emp-002',
    employeeNumber: 'E-1002',
    name: 'Sara Khan',
    email: 'sara.khan@acme.com',
    mobile: '+92-300-1000002',
    corporateId: 'corp-001',
    planId: 'plan-acme-gold-2025',
    coverageStart: '2025-01-01',
    coverageEnd: '2025-12-31',
    designation: 'Product Manager',
    department: 'Product',
    cnic: '42101-2345678-2',
    dob: '1996-07-22',
    gender: 'Female',
    address: 'Flat 4B, Bahria Town Phase 7, Rawalpindi',
  },
  {
    id: 'emp-003',
    employeeNumber: 'E-1003',
    name: 'Omar Malik',
    email: 'omar.malik@acme.com',
    mobile: '+92-300-1000003',
    corporateId: 'corp-001',
    planId: 'plan-acme-basic-2025',
    coverageStart: '2025-01-01',
    coverageEnd: '2025-12-31',
    designation: 'Analyst',
    department: 'Finance',
    cnic: '42101-3456789-3',
    dob: '1984-11-08',
    gender: 'Male',
    address: 'House 89, DHA Phase 2, Islamabad',
  },
  {
    id: 'emp-004',
    employeeNumber: 'E-1004',
    name: 'Hina Javed',
    email: 'hina.javed@acme.com',
    mobile: '+92-300-1000004',
    corporateId: 'corp-001',
    planId: 'plan-acme-basic-2025',
    coverageStart: '2025-01-01',
    coverageEnd: '2025-12-31',
    designation: 'HR',
    department: 'People',
    cnic: '42101-4567890-4',
    dob: '1998-04-14',
    gender: 'Female',
    address: 'Apartment 12, G-10 Markaz, Islamabad',
  },
  {
    id: 'emp-005',
    employeeNumber: 'E-2001',
    name: 'Bilal Khan',
    email: 'bilal.khan@beta.com',
    mobile: '+92-300-2000001',
    corporateId: 'corp-002',
    planId: 'plan-beta-silver-2025',
    coverageStart: '2025-01-01',
    coverageEnd: '2025-12-31',
    designation: 'DevOps',
    department: 'IT',
    cnic: '42201-1234567-5',
    dob: '1993-09-25',
    gender: 'Male',
    address: 'House 45, Gulberg III, Lahore',
  },
  {
    id: 'emp-006',
    employeeNumber: 'E-2002',
    name: 'Nadia Farooq',
    email: 'nadia.farooq@beta.com',
    mobile: '+92-300-2000002',
    corporateId: 'corp-002',
    planId: 'plan-beta-silver-2025',
    coverageStart: '2025-01-01',
    coverageEnd: '2025-12-31',
    designation: 'QA',
    department: 'Engineering',
    cnic: '42201-2345678-6',
    dob: '1995-06-18',
    gender: 'Female',
    address: 'Flat 8C, Johar Town, Lahore',
  },
  {
    id: 'emp-007',
    employeeNumber: 'E-2003',
    name: 'Imran Qureshi',
    email: 'imran.qu@beta.com',
    mobile: '+92-300-2000003',
    corporateId: 'corp-002',
    planId: 'plan-beta-basic-2025',
    coverageStart: '2025-01-01',
    coverageEnd: '2025-12-31',
    designation: 'Sales',
    department: 'Sales',
    cnic: '42201-3456789-7',
    dob: '1987-12-03',
    gender: 'Male',
    address: 'House 23, Model Town, Lahore',
  },
  {
    id: 'emp-008',
    employeeNumber: 'E-2004',
    name: 'Maya Ali',
    email: 'maya.ali@beta.com',
    mobile: '+92-300-2000004',
    corporateId: 'corp-002',
    planId: 'plan-beta-basic-2025',
    coverageStart: '2025-01-01',
    coverageEnd: '2025-12-31',
    designation: 'Accountant',
    department: 'Finance',
    cnic: '42201-4567890-8',
    dob: '1999-08-11',
    gender: 'Female',
    address: 'Apartment 5A, DHA Phase 5, Lahore',
  },
  {
    id: 'emp-009',
    employeeNumber: 'E-3001',
    name: 'Fahad Ahmed',
    email: 'fahad.ahmed@noorfoods.com',
    mobile: '+92-300-3000001',
    corporateId: 'corp-003',
    planId: 'plan-noor-gold-2025',
    coverageStart: '2025-02-01',
    coverageEnd: '2026-01-31',
    designation: 'Operations',
    department: 'Logistics',
    cnic: '42301-1234567-9',
    dob: '1990-05-20',
    gender: 'Male',
    address: 'House 67, Clifton Block 2, Karachi',
  },
  {
    id: 'emp-010',
    employeeNumber: 'E-3002',
    name: 'Sana Rafi',
    email: 'sana.rafi@noorfoods.com',
    mobile: '+92-300-3000002',
    corporateId: 'corp-003',
    planId: 'plan-noor-gold-2025',
    coverageStart: '2025-02-01',
    coverageEnd: '2026-01-31',
    designation: 'Chef',
    department: 'Production',
    cnic: '42301-2345678-0',
    dob: '1992-02-28',
    gender: 'Female',
    address: 'Flat 12D, Gulshan-e-Iqbal, Karachi',
  },
  {
    id: 'emp-011',
    employeeNumber: 'E-3003',
    name: 'Khalid Azam',
    email: 'khalid.azam@noorfoods.com',
    mobile: '+92-300-3000003',
    corporateId: 'corp-003',
    planId: 'plan-noor-basic-2025',
    coverageStart: '2025-02-01',
    coverageEnd: '2026-01-31',
    designation: 'Driver',
    department: 'Logistics',
    cnic: '42301-3456789-1',
    dob: '1981-10-12',
    gender: 'Male',
    address: 'House 34, North Nazimabad, Karachi',
  },
  {
    id: 'emp-012',
    employeeNumber: 'E-1005',
    name: 'Amna Iqbal',
    email: 'amna.iqbal@acme.com',
    mobile: '+92-300-1000005',
    corporateId: 'corp-001',
    planId: 'plan-acme-gold-2025',
    coverageStart: '2025-01-01',
    coverageEnd: '2025-12-31',
    designation: 'Designer',
    department: 'Design',
    cnic: '42101-5678901-2',
    dob: '1997-01-09',
    gender: 'Female',
    address: 'House 56, I-9/3, Islamabad',
  },
  {
    id: 'emp-013',
    employeeNumber: 'E-1006',
    name: 'Usman Rafi',
    email: 'usman.rafi@acme.com',
    mobile: '+92-300-1000006',
    corporateId: 'corp-001',
    planId: 'plan-acme-basic-2025',
    coverageStart: '2025-01-01',
    coverageEnd: '2025-12-31',
    designation: 'Support',
    department: 'Customer',
    cnic: '42101-6789012-3',
    dob: '1994-07-17',
    gender: 'Male',
    address: 'Flat 3B, F-11 Markaz, Islamabad',
  },
  {
    id: 'emp-014',
    employeeNumber: 'E-2005',
    name: 'Zara Khan',
    email: 'zara.khan@beta.com',
    mobile: '+92-300-2000005',
    corporateId: 'corp-002',
    planId: 'plan-beta-silver-2025',
    coverageStart: '2025-01-01',
    coverageEnd: '2025-12-31',
    designation: 'HR',
    department: 'People',
    cnic: '42201-5678901-4',
    dob: '1996-11-23',
    gender: 'Female',
    address: 'House 78, Wapda Town, Lahore',
  },
  {
    id: 'emp-015',
    employeeNumber: 'E-2006',
    name: 'Rashid Noor',
    email: 'rashid.noor@beta.com',
    mobile: '+92-300-2000006',
    corporateId: 'corp-002',
    planId: 'plan-beta-basic-2025',
    coverageStart: '2025-01-01',
    coverageEnd: '2025-12-31',
    designation: 'Sales',
    department: 'Sales',
    cnic: '42201-6789012-5',
    dob: '1989-04-05',
    gender: 'Male',
    address: 'Apartment 9D, Garden Town, Lahore',
  },
  {
    id: 'emp-016',
    employeeNumber: 'E-3004',
    name: 'Ayesha Mir',
    email: 'ayesha.mir@noorfoods.com',
    mobile: '+92-300-3000004',
    corporateId: 'corp-003',
    planId: 'plan-noor-basic-2025',
    coverageStart: '2025-02-01',
    coverageEnd: '2026-01-31',
    designation: 'Packing',
    department: 'Production',
    cnic: '42301-4567890-2',
    dob: '2000-09-14',
    gender: 'Female',
    address: 'House 22, Korangi Industrial Area, Karachi',
  },
  {
    id: 'emp-017',
    employeeNumber: 'E-3005',
    name: 'Tariq Mahmood',
    email: 'tariq.mahmood@noorfoods.com',
    mobile: '+92-300-3000005',
    corporateId: 'corp-003',
    planId: 'plan-noor-gold-2025',
    coverageStart: '2025-02-01',
    coverageEnd: '2026-01-31',
    designation: 'Supervisor',
    department: 'Quality',
    cnic: '42301-5678901-3',
    dob: '1983-03-07',
    gender: 'Male',
    address: 'Flat 7C, Bahadurabad, Karachi',
  },
  {
    id: 'emp-018',
    employeeNumber: 'E-1007',
    name: 'Naveed Khan',
    email: 'naveed.khan@acme.com',
    mobile: '+92-300-1000007',
    corporateId: 'corp-001',
    planId: 'plan-acme-gold-2025',
    coverageStart: '2025-01-01',
    coverageEnd: '2025-12-31',
    designation: 'Manager',
    department: 'Operations',
    cnic: '42101-7890123-4',
    dob: '1986-06-26',
    gender: 'Male',
    address: 'House 91, G-13/1, Islamabad',
  },
  {
    id: 'emp-019',
    employeeNumber: 'E-2007',
    name: 'Mehwish Ali',
    email: 'mehwish.ali@beta.com',
    mobile: '+92-300-2000007',
    corporateId: 'corp-002',
    planId: 'plan-beta-silver-2025',
    coverageStart: '2025-01-01',
    coverageEnd: '2025-12-31',
    designation: 'Engineer',
    department: 'R&D',
    cnic: '42201-7890123-6',
    dob: '1995-12-19',
    gender: 'Female',
    address: 'House 42, Defense Phase 6, Lahore',
  },
  {
    id: 'emp-020',
    employeeNumber: 'E-1008',
    name: 'Zubair Ahmed',
    email: 'zubair.ahmed@acme.com',
    mobile: '+92-300-1000008',
    corporateId: 'corp-001',
    planId: 'plan-acme-basic-2025',
    coverageStart: '2025-01-01',
    coverageEnd: '2025-12-31',
    designation: 'Technician',
    department: 'Maintenance',
    cnic: '42101-8901234-5',
    dob: '1988-08-30',
    gender: 'Male',
    address: 'Flat 11A, Blue Area, Islamabad',
  },
];

// ---- HOSPITALS (from hospitals.json — all 40) ----
interface HospitalData {
  id: string;
  name: string;
  city: string;
  type: 'reimbursable' | 'non_reimbursable';
  contact: string;
  address: string;
  lat?: number;
  lng?: number;
  hasEmergency?: boolean;
}

const hospitals: HospitalData[] = [
  {
    id: 'hosp-001',
    name: 'City General Hospital',
    city: 'Islamabad',
    type: 'reimbursable',
    contact: '+92-51-1234567',
    address: 'Main Boulevard, Sector F-7, Islamabad',
    lat: 33.7215,
    lng: 73.0433,
    hasEmergency: true,
  },
  {
    id: 'hosp-002',
    name: 'National Hospital',
    city: 'Lahore',
    type: 'reimbursable',
    contact: '+92-42-2345678',
    address: 'MM Alam Road, Gulberg, Lahore',
    lat: 31.5204,
    lng: 74.3587,
    hasEmergency: true,
  },
  {
    id: 'hosp-003',
    name: 'Aga Khan University Hospital',
    city: 'Karachi',
    type: 'reimbursable',
    contact: '+92-21-34930000',
    address: 'Stadium Road, Karachi',
    lat: 24.8927,
    lng: 67.0741,
    hasEmergency: true,
  },
  {
    id: 'hosp-004',
    name: 'Services Hospital',
    city: 'Lahore',
    type: 'reimbursable',
    contact: '+92-42-99211101',
    address: 'Shahrah-e-Abbas, Lahore',
    lat: 31.5497,
    lng: 74.3436,
    hasEmergency: true,
  },
  {
    id: 'hosp-005',
    name: 'Jinnah Hospital',
    city: 'Lahore',
    type: 'reimbursable',
    contact: '+92-42-99231401',
    address: 'Allama Iqbal Road, Lahore',
    lat: 31.5127,
    lng: 74.3461,
    hasEmergency: true,
  },
  {
    id: 'hosp-006',
    name: 'Civil Hospital',
    city: 'Karachi',
    type: 'reimbursable',
    contact: '+92-21-99215740',
    address: 'Hospital Road, Karachi',
    lat: 24.8594,
    lng: 67.0103,
    hasEmergency: true,
  },
  {
    id: 'hosp-007',
    name: 'Holy Family Hospital',
    city: 'Rawalpindi',
    type: 'reimbursable',
    contact: '+92-51-9290301',
    address: 'Satellite Town, Rawalpindi',
    lat: 33.6007,
    lng: 73.0679,
    hasEmergency: true,
  },
  {
    id: 'hosp-008',
    name: 'Omar Hospital',
    city: 'Islamabad',
    type: 'reimbursable',
    contact: '+92-51-2890401',
    address: 'Blue Area, Islamabad',
    lat: 33.7294,
    lng: 73.0931,
    hasEmergency: true,
  },
  {
    id: 'hosp-009',
    name: 'Shifa International Hospital',
    city: 'Islamabad',
    type: 'reimbursable',
    contact: '+92-51-8464646',
    address: 'Pitras Bukhari Road, H-8/4, Islamabad',
    lat: 33.6844,
    lng: 73.0479,
    hasEmergency: true,
  },
  {
    id: 'hosp-010',
    name: 'Mayo Hospital',
    city: 'Lahore',
    type: 'reimbursable',
    contact: '+92-42-99211130',
    address: 'Neela Gumbad, Anarkali, Lahore',
    lat: 31.5659,
    lng: 74.3234,
    hasEmergency: true,
  },
  {
    id: 'hosp-011',
    name: 'Lady Reading Hospital',
    city: 'Peshawar',
    type: 'reimbursable',
    contact: '+92-91-9211430',
    address: 'Hospital Road, Peshawar',
    lat: 34.0151,
    lng: 71.5249,
    hasEmergency: true,
  },
  {
    id: 'hosp-012',
    name: 'Fatima Jinnah Hospital',
    city: 'Quetta',
    type: 'reimbursable',
    contact: '+92-81-9202331',
    address: 'Shahrah-e-Zarghoon, Quetta',
    lat: 30.1798,
    lng: 66.975,
    hasEmergency: true,
  },
  // Non-reimbursable hospitals (13-40)
  {
    id: 'hosp-013',
    name: 'Life Care Hospital',
    city: 'Islamabad',
    type: 'non_reimbursable',
    contact: '+92-51-2890501',
    address: 'F-10 Markaz, Islamabad',
  },
  {
    id: 'hosp-014',
    name: 'Mussawaar Welfare General Hospital',
    city: 'Gojra',
    type: 'non_reimbursable',
    contact: '+92-46-3510123',
    address: 'Main Road, Gojra',
  },
  {
    id: 'hosp-015',
    name: 'Essa General Hospital',
    city: 'Karachi',
    type: 'non_reimbursable',
    contact: '+92-21-32734101',
    address: 'Nazimabad, Karachi',
  },
  {
    id: 'hosp-016',
    name: 'Nehal Hospital',
    city: 'Karachi',
    type: 'non_reimbursable',
    contact: '+92-21-36603001',
    address: 'Gulshan-e-Iqbal, Karachi',
  },
  {
    id: 'hosp-017',
    name: 'Hassan General Hospital',
    city: 'Karachi',
    type: 'non_reimbursable',
    contact: '+92-21-36820001',
    address: 'North Karachi, Karachi',
  },
  {
    id: 'hosp-018',
    name: 'Timaz General Hospital',
    city: 'Karachi',
    type: 'non_reimbursable',
    contact: '+92-21-34820001',
    address: 'Malir, Karachi',
  },
  {
    id: 'hosp-019',
    name: 'Asfar Memorial Hospital',
    city: 'Karachi',
    type: 'non_reimbursable',
    contact: '+92-21-34120001',
    address: 'Korangi, Karachi',
  },
  {
    id: 'hosp-020',
    name: 'Ayesha General Hospital',
    city: 'Karachi',
    type: 'non_reimbursable',
    contact: '+92-21-35820001',
    address: 'SITE Area, Karachi',
  },
  {
    id: 'hosp-021',
    name: 'Sir Syed Hospital',
    city: 'Karachi',
    type: 'non_reimbursable',
    contact: '+92-21-34990001',
    address: 'Nazimabad No. 4, Karachi',
  },
  {
    id: 'hosp-022',
    name: 'Plastic Surgery General Hospital',
    city: 'Karachi',
    type: 'non_reimbursable',
    contact: '+92-21-35110001',
    address: 'Burns Garden, Karachi',
  },
  {
    id: 'hosp-023',
    name: 'Hafiz Medical Centre',
    city: 'Karachi',
    type: 'non_reimbursable',
    contact: '+92-21-36360001',
    address: 'FB Area, Karachi',
  },
  {
    id: 'hosp-024',
    name: 'New Urgent Care Hospital',
    city: 'Karachi',
    type: 'non_reimbursable',
    contact: '+92-21-36610001',
    address: 'Gulistan-e-Johar, Karachi',
  },
  {
    id: 'hosp-025',
    name: 'Samdani Hospital',
    city: 'Karachi',
    type: 'non_reimbursable',
    contact: '+92-21-36680001',
    address: 'North Nazimabad, Karachi',
  },
  {
    id: 'hosp-026',
    name: 'Khursheed Rafiq Hospital',
    city: 'Multan',
    type: 'non_reimbursable',
    contact: '+92-61-4510001',
    address: 'Bosan Road, Multan',
  },
  {
    id: 'hosp-027',
    name: 'Razia Saeed Hospital',
    city: 'Multan',
    type: 'non_reimbursable',
    contact: '+92-61-4520001',
    address: 'Shah Rukn-e-Alam Colony, Multan',
  },
  {
    id: 'hosp-028',
    name: 'Bismillah Hospital',
    city: 'Karachi',
    type: 'non_reimbursable',
    contact: '+92-21-32250001',
    address: 'Lyari, Karachi',
  },
  {
    id: 'hosp-029',
    name: 'Infinity Eye Care Centre',
    city: 'Karachi',
    type: 'non_reimbursable',
    contact: '+92-21-35870001',
    address: 'Clifton, Karachi',
  },
  {
    id: 'hosp-030',
    name: 'Sherazi Hospital',
    city: 'Lahore',
    type: 'non_reimbursable',
    contact: '+92-42-37110001',
    address: 'Shadman, Lahore',
  },
  {
    id: 'hosp-031',
    name: 'Shamim Hospital',
    city: 'Lahore',
    type: 'non_reimbursable',
    contact: '+92-42-37420001',
    address: 'Samanabad, Lahore',
  },
  {
    id: 'hosp-032',
    name: 'Al-Khyber General Hospital',
    city: 'Karachi',
    type: 'non_reimbursable',
    contact: '+92-21-36770001',
    address: 'Orangi Town, Karachi',
  },
  {
    id: 'hosp-033',
    name: 'Shah Medical Center',
    city: 'Karachi',
    type: 'non_reimbursable',
    contact: '+92-21-34880001',
    address: 'Malir Cantt, Karachi',
  },
  {
    id: 'hosp-034',
    name: 'Rana Hospital',
    city: 'Lahore',
    type: 'non_reimbursable',
    contact: '+92-42-36310001',
    address: 'Township, Lahore',
  },
  {
    id: 'hosp-035',
    name: 'Iffat Anver Medical Complex',
    city: 'Lahore',
    type: 'non_reimbursable',
    contact: '+92-42-35180001',
    address: 'Faisal Town, Lahore',
  },
  {
    id: 'hosp-036',
    name: 'Umar Surgical Hospital',
    city: 'Lodhran',
    type: 'non_reimbursable',
    contact: '+92-608-362001',
    address: 'Main Bazaar, Lodhran',
  },
  {
    id: 'hosp-037',
    name: 'Rehman Medical Center',
    city: 'Jacobabad',
    type: 'non_reimbursable',
    contact: '+92-722-651001',
    address: 'Civil Lines, Jacobabad',
  },
  {
    id: 'hosp-038',
    name: 'Sughrra Hospital',
    city: 'Jhelum',
    type: 'non_reimbursable',
    contact: '+92-544-621001',
    address: 'GT Road, Jhelum',
  },
  {
    id: 'hosp-039',
    name: 'Dr Fida Painless Hospital',
    city: 'Peshawar',
    type: 'non_reimbursable',
    contact: '+92-91-5840001',
    address: 'University Road, Peshawar',
  },
  {
    id: 'hosp-040',
    name: 'Rehmat Jan Medical Center',
    city: 'Karachi',
    type: 'non_reimbursable',
    contact: '+92-21-35990001',
    address: 'Landhi, Karachi',
  },
];

// ---- PLANS (from plans.json) ----
interface PlanData {
  id: string;
  name: string;
  planCode: string;
  sumInsured: number;
  coveredServices: string[];
  limits: Record<string, number>;
  validFrom: string;
  validUntil: string;
}

const plans: PlanData[] = [
  {
    id: 'plan-acme-gold-2025',
    name: 'Acme Gold Group 2025',
    planCode: 'ACME-GOLD-2025',
    sumInsured: 2000000,
    coveredServices: ['IPD', 'OPD', 'Maternity', 'Diagnostics'],
    limits: { OPDPerYear: 10000, MaternityLimit: 250000 },
    validFrom: '2025-01-01',
    validUntil: '2025-12-31',
  },
  {
    id: 'plan-acme-basic-2025',
    name: 'Acme Basic Group 2025',
    planCode: 'ACME-BASIC-2025',
    sumInsured: 500000,
    coveredServices: ['IPD', 'OPD'],
    limits: { OPDPerYear: 5000 },
    validFrom: '2025-01-01',
    validUntil: '2025-12-31',
  },
  {
    id: 'plan-beta-silver-2025',
    name: 'Beta Silver Group 2025',
    planCode: 'BETA-SILVER-2025',
    sumInsured: 1000000,
    coveredServices: ['IPD', 'OPD', 'Diagnostics'],
    limits: { OPDPerYear: 8000 },
    validFrom: '2025-01-01',
    validUntil: '2025-12-31',
  },
  {
    id: 'plan-beta-basic-2025',
    name: 'Beta Basic 2025',
    planCode: 'BETA-BASIC-2025',
    sumInsured: 400000,
    coveredServices: ['IPD', 'OPD'],
    limits: { OPDPerYear: 4000 },
    validFrom: '2025-01-01',
    validUntil: '2025-12-31',
  },
  {
    id: 'plan-noor-gold-2025',
    name: 'Noor Gold Group 2025',
    planCode: 'NOOR-GOLD-2025',
    sumInsured: 1500000,
    coveredServices: ['IPD', 'OPD', 'Maternity'],
    limits: { OPDPerYear: 9000, MaternityLimit: 200000 },
    validFrom: '2025-02-01',
    validUntil: '2026-01-31',
  },
  {
    id: 'plan-noor-basic-2025',
    name: 'Noor Basic 2025',
    planCode: 'NOOR-BASIC-2025',
    sumInsured: 500000,
    coveredServices: ['IPD', 'OPD'],
    limits: { OPDPerYear: 5000 },
    validFrom: '2025-02-01',
    validUntil: '2026-01-31',
  },
];

// ---- CLAIMS (from claims.json) ----
interface ClaimEventData {
  ts: string;
  actorName: string;
  actorRole: string;
  action: string;
  from: string | null;
  to: string;
  note?: string;
}

interface ClaimData {
  id: string;
  claimNumber: string;
  employeeId: string;
  corporateId: string;
  hospitalId: string;
  planId: string;
  status: 'Pending' | 'Approved' | 'Rejected';
  amountClaimed: number;
  approvedAmount: number;
  treatmentCategory: string;
  admissionDate: string;
  dischargeDate: string;
  events: ClaimEventData[];
  createdAt: string;
  priority: 'Normal' | 'High';
}

const claims: ClaimData[] = [
  {
    id: 'clm-0001',
    claimNumber: 'CLM-2025-0001',
    employeeId: 'emp-001',
    corporateId: 'corp-001',
    hospitalId: 'hosp-001',
    planId: 'plan-acme-gold-2025',
    status: 'Pending',
    amountClaimed: 125000,
    approvedAmount: 0,
    treatmentCategory: 'Surgery',
    admissionDate: '2025-10-02',
    dischargeDate: '2025-10-04',
    events: [
      {
        ts: '2025-10-04T08:30:00Z',
        actorName: 'Ali Raza',
        actorRole: 'Employee',
        action: 'Submitted claim',
        from: null,
        to: 'Pending',
      },
    ],
    createdAt: '2025-10-04T08:30:00Z',
    priority: 'Normal',
  },
  {
    id: 'clm-0001a',
    claimNumber: 'CLM-2025-0001A',
    employeeId: 'emp-001',
    corporateId: 'corp-001',
    hospitalId: 'hosp-002',
    planId: 'plan-acme-gold-2025',
    status: 'Approved',
    amountClaimed: 45000,
    approvedAmount: 45000,
    treatmentCategory: 'Consultation',
    admissionDate: '2025-10-01',
    dischargeDate: '2025-10-02',
    events: [
      {
        ts: '2025-10-02T10:00:00Z',
        actorName: 'Ali Raza',
        actorRole: 'Employee',
        action: 'Submitted claim',
        from: null,
        to: 'Pending',
      },
      {
        ts: '2025-10-03T14:30:00Z',
        actorName: 'Claims Team',
        actorRole: 'Insurer',
        action: 'Approved claim',
        from: 'Pending',
        to: 'Approved',
      },
    ],
    createdAt: '2025-10-02T10:00:00Z',
    priority: 'Normal',
  },
  {
    id: 'clm-0001b',
    claimNumber: 'CLM-2025-0001B',
    employeeId: 'emp-001',
    corporateId: 'corp-001',
    hospitalId: 'hosp-003',
    planId: 'plan-acme-gold-2025',
    status: 'Approved',
    amountClaimed: 78000,
    approvedAmount: 78000,
    treatmentCategory: 'Lab Tests',
    admissionDate: '2025-09-30',
    dischargeDate: '2025-10-01',
    events: [
      {
        ts: '2025-10-01T11:15:00Z',
        actorName: 'Ali Raza',
        actorRole: 'Employee',
        action: 'Submitted claim',
        from: null,
        to: 'Pending',
      },
      {
        ts: '2025-10-01T09:45:00Z',
        actorName: 'Claims Team',
        actorRole: 'Insurer',
        action: 'Approved claim',
        from: 'Pending',
        to: 'Approved',
      },
    ],
    createdAt: '2025-10-01T11:15:00Z',
    priority: 'Normal',
  },
  {
    id: 'clm-0002',
    claimNumber: 'CLM-2025-0002',
    employeeId: 'emp-002',
    corporateId: 'corp-001',
    hospitalId: 'hosp-002',
    planId: 'plan-acme-gold-2025',
    status: 'Pending',
    amountClaimed: 18000,
    approvedAmount: 0,
    treatmentCategory: 'Routine Checkup',
    admissionDate: '2025-10-01',
    dischargeDate: '2025-10-01',
    events: [
      {
        ts: '2025-10-01T09:10:00Z',
        actorName: 'Sara Khan',
        actorRole: 'Employee',
        action: 'Submitted claim',
        from: null,
        to: 'Pending',
      },
      {
        ts: '2025-10-01T11:00:00Z',
        actorName: 'Dr. Naveed',
        actorRole: 'Hospital',
        action: 'Uploaded documents',
        from: 'Pending',
        to: 'Pending',
      },
    ],
    createdAt: '2025-10-01T09:10:00Z',
    priority: 'Normal',
  },
  {
    id: 'clm-0003',
    claimNumber: 'CLM-2025-0003',
    employeeId: 'emp-005',
    corporateId: 'corp-002',
    hospitalId: 'hosp-004',
    planId: 'plan-beta-silver-2025',
    status: 'Pending',
    amountClaimed: 42000,
    approvedAmount: 0,
    treatmentCategory: 'Routine Checkup',
    admissionDate: '2025-09-20',
    dischargeDate: '2025-09-22',
    events: [
      {
        ts: '2025-09-22T10:00:00Z',
        actorName: 'Bilal Khan',
        actorRole: 'Employee',
        action: 'Submitted claim',
        from: null,
        to: 'Pending',
      },
      {
        ts: '2025-09-22T15:30:00Z',
        actorName: 'Crescent Staff',
        actorRole: 'Hospital',
        action: 'Uploaded documents',
        from: 'Pending',
        to: 'Pending',
      },
      {
        ts: '2025-09-23T09:00:00Z',
        actorName: 'Leena Shah',
        actorRole: 'Claims Adjuster',
        action: 'Started review',
        from: 'Pending',
        to: 'Pending',
      },
    ],
    createdAt: '2025-09-22T10:00:00Z',
    priority: 'Normal',
  },
  {
    id: 'clm-0004',
    claimNumber: 'CLM-2025-0004',
    employeeId: 'emp-009',
    corporateId: 'corp-003',
    hospitalId: 'hosp-003',
    planId: 'plan-noor-gold-2025',
    status: 'Pending',
    amountClaimed: 32000,
    approvedAmount: 0,
    treatmentCategory: 'Routine Checkup',
    admissionDate: '2025-09-25',
    dischargeDate: '2025-09-26',
    events: [
      {
        ts: '2025-09-26T08:45:00Z',
        actorName: 'Fahad Ahmed',
        actorRole: 'Employee',
        action: 'Submitted claim',
        from: null,
        to: 'Pending',
      },
      {
        ts: '2025-09-26T12:00:00Z',
        actorName: 'NorthCare Staff',
        actorRole: 'Hospital',
        action: 'Uploaded documents',
        from: 'Pending',
        to: 'Pending',
      },
      {
        ts: '2025-09-27T14:30:00Z',
        actorName: 'Leena Shah',
        actorRole: 'Claims Adjuster',
        action: 'Requested more information',
        from: 'Pending',
        to: 'Pending',
        note: 'Missing lab report',
      },
    ],
    createdAt: '2025-09-26T08:45:00Z',
    priority: 'Normal',
  },
  {
    id: 'clm-0005',
    claimNumber: 'CLM-2025-0005',
    employeeId: 'emp-010',
    corporateId: 'corp-003',
    hospitalId: 'hosp-005',
    planId: 'plan-noor-gold-2025',
    status: 'Pending',
    amountClaimed: 90000,
    approvedAmount: 0,
    treatmentCategory: 'Cardiology',
    admissionDate: '2025-09-10',
    dischargeDate: '2025-09-15',
    events: [
      {
        ts: '2025-09-15T09:00:00Z',
        actorName: 'Sana Rafi',
        actorRole: 'Employee',
        action: 'Submitted claim',
        from: null,
        to: 'Pending',
      },
      {
        ts: '2025-09-15T11:00:00Z',
        actorName: 'Lakeside Staff',
        actorRole: 'Hospital',
        action: 'Uploaded documents',
        from: 'Pending',
        to: 'Pending',
      },
      {
        ts: '2025-09-17T10:30:00Z',
        actorName: 'Ayesha Khan',
        actorRole: 'Claims Manager',
        action: 'Approved by medical officer',
        from: 'Pending',
        to: 'Pending',
        note: 'Recommend approval subject to finance',
      },
    ],
    createdAt: '2025-09-15T09:00:00Z',
    priority: 'High',
  },
  {
    id: 'clm-0006',
    claimNumber: 'CLM-2025-0006',
    employeeId: 'emp-006',
    corporateId: 'corp-002',
    hospitalId: 'hosp-004',
    planId: 'plan-beta-silver-2025',
    status: 'Approved',
    amountClaimed: 15000,
    approvedAmount: 13500,
    treatmentCategory: 'Routine Checkup',
    admissionDate: '2025-09-05',
    dischargeDate: '2025-09-05',
    events: [
      {
        ts: '2025-09-05T07:50:00Z',
        actorName: 'Nadia Farooq',
        actorRole: 'Employee',
        action: 'Submitted claim',
        from: null,
        to: 'Pending',
      },
      {
        ts: '2025-09-05T10:00:00Z',
        actorName: 'Crescent Staff',
        actorRole: 'Hospital',
        action: 'Uploaded documents',
        from: 'Pending',
        to: 'Pending',
      },
      {
        ts: '2025-09-06T13:00:00Z',
        actorName: 'Leena Shah',
        actorRole: 'Claims Adjuster',
        action: 'Approved claim',
        from: 'Pending',
        to: 'Approved',
        note: 'Approved with 10% copay',
      },
    ],
    createdAt: '2025-09-05T07:50:00Z',
    priority: 'Normal',
  },
  {
    id: 'clm-0007',
    claimNumber: 'CLM-2025-0007',
    employeeId: 'emp-003',
    corporateId: 'corp-001',
    hospitalId: 'hosp-002',
    planId: 'plan-acme-basic-2025',
    status: 'Rejected',
    amountClaimed: 8000,
    approvedAmount: 0,
    treatmentCategory: 'Lab Test',
    admissionDate: '2025-08-20',
    dischargeDate: '2025-08-20',
    events: [
      {
        ts: '2025-08-20T09:00:00Z',
        actorName: 'Omar Malik',
        actorRole: 'Employee',
        action: 'Submitted claim',
        from: null,
        to: 'Pending',
      },
      {
        ts: '2025-08-20T12:00:00Z',
        actorName: 'Eastside Staff',
        actorRole: 'Hospital',
        action: 'Uploaded documents',
        from: 'Pending',
        to: 'Pending',
      },
      {
        ts: '2025-08-22T10:00:00Z',
        actorName: 'Bilal Ahmed',
        actorRole: 'Medical Officer',
        action: 'Rejected claim',
        from: 'Pending',
        to: 'Rejected',
        note: 'Procedure not covered',
      },
    ],
    createdAt: '2025-08-20T09:00:00Z',
    priority: 'Normal',
  },
  {
    id: 'clm-0008',
    claimNumber: 'CLM-2025-0008',
    employeeId: 'emp-007',
    corporateId: 'corp-002',
    hospitalId: 'hosp-001',
    planId: 'plan-beta-basic-2025',
    status: 'Approved',
    amountClaimed: 22000,
    approvedAmount: 19800,
    treatmentCategory: 'Routine Checkup',
    admissionDate: '2025-08-30',
    dischargeDate: '2025-09-02',
    events: [
      {
        ts: '2025-08-30T08:00:00Z',
        actorName: 'Imran Qureshi',
        actorRole: 'Employee',
        action: 'Submitted claim',
        from: null,
        to: 'Pending',
      },
      {
        ts: '2025-08-30T10:00:00Z',
        actorName: 'City General Staff',
        actorRole: 'Hospital',
        action: 'Uploaded documents',
        from: 'Pending',
        to: 'Pending',
      },
      {
        ts: '2025-09-02T14:00:00Z',
        actorName: 'Leena Shah',
        actorRole: 'Claims Adjuster',
        action: 'Approved claim',
        from: 'Pending',
        to: 'Approved',
      },
      {
        ts: '2025-09-04T09:30:00Z',
        actorName: 'Finance',
        actorRole: 'InsurerFinance',
        action: 'Payment issued',
        from: 'Approved',
        to: 'Approved',
        note: 'Transaction tr-2001',
      },
    ],
    createdAt: '2025-08-30T08:00:00Z',
    priority: 'Normal',
  },
  {
    id: 'clm-0009',
    claimNumber: 'CLM-2025-0009',
    employeeId: 'emp-012',
    corporateId: 'corp-001',
    hospitalId: 'hosp-004',
    planId: 'plan-acme-gold-2025',
    status: 'Approved',
    amountClaimed: 6000,
    approvedAmount: 5400,
    treatmentCategory: 'Lab Test',
    admissionDate: '2025-09-07',
    dischargeDate: '2025-09-07',
    events: [
      {
        ts: '2025-09-07T07:30:00Z',
        actorName: 'Amna Iqbal',
        actorRole: 'Employee',
        action: 'Submitted claim',
        from: null,
        to: 'Pending',
      },
      {
        ts: '2025-09-07T09:00:00Z',
        actorName: 'Crescent Staff',
        actorRole: 'Hospital',
        action: 'Uploaded documents',
        from: 'Pending',
        to: 'Pending',
      },
      {
        ts: '2025-09-08T12:00:00Z',
        actorName: 'Ayesha Khan',
        actorRole: 'Claims Manager',
        action: 'Approved claim',
        from: 'Pending',
        to: 'Approved',
      },
    ],
    createdAt: '2025-09-07T07:30:00Z',
    priority: 'Normal',
  },
  {
    id: 'clm-0010',
    claimNumber: 'CLM-2025-0010',
    employeeId: 'emp-014',
    corporateId: 'corp-002',
    hospitalId: 'hosp-002',
    planId: 'plan-beta-silver-2025',
    status: 'Pending',
    amountClaimed: 4500,
    approvedAmount: 0,
    treatmentCategory: 'Lab Test',
    admissionDate: '2025-10-02',
    dischargeDate: '2025-10-02',
    events: [
      {
        ts: '2025-10-02T08:10:00Z',
        actorName: 'Zara Khan',
        actorRole: 'Employee',
        action: 'Submitted claim',
        from: null,
        to: 'Pending',
      },
      {
        ts: '2025-10-02T09:40:00Z',
        actorName: 'Eastside Staff',
        actorRole: 'Hospital',
        action: 'Uploaded documents',
        from: 'Pending',
        to: 'Pending',
      },
    ],
    createdAt: '2025-10-02T08:10:00Z',
    priority: 'Normal',
  },
  {
    id: 'clm-0011',
    claimNumber: 'CLM-2025-0011',
    employeeId: 'emp-016',
    corporateId: 'corp-003',
    hospitalId: 'hosp-005',
    planId: 'plan-noor-basic-2025',
    status: 'Pending',
    amountClaimed: 27500,
    approvedAmount: 0,
    treatmentCategory: 'Routine Checkup',
    admissionDate: '2025-09-18',
    dischargeDate: '2025-09-19',
    events: [
      {
        ts: '2025-09-19T08:00:00Z',
        actorName: 'Ayesha Mir',
        actorRole: 'Employee',
        action: 'Submitted claim',
        from: null,
        to: 'Pending',
      },
      {
        ts: '2025-09-19T10:30:00Z',
        actorName: 'Lakeside Staff',
        actorRole: 'Hospital',
        action: 'Uploaded documents',
        from: 'Pending',
        to: 'Pending',
      },
      {
        ts: '2025-09-20T09:00:00Z',
        actorName: 'Leena Shah',
        actorRole: 'Claims Adjuster',
        action: 'Started review',
        from: 'Pending',
        to: 'Pending',
      },
    ],
    createdAt: '2025-09-19T08:00:00Z',
    priority: 'Normal',
  },
  {
    id: 'clm-0012',
    claimNumber: 'CLM-2025-0012',
    employeeId: 'emp-020',
    corporateId: 'corp-001',
    hospitalId: 'hosp-001',
    planId: 'plan-acme-basic-2025',
    status: 'Pending',
    amountClaimed: 6500,
    approvedAmount: 0,
    treatmentCategory: 'Lab Test',
    admissionDate: '2025-10-04',
    dischargeDate: '2025-10-04',
    events: [
      {
        ts: '2025-10-04T07:40:00Z',
        actorName: 'Zubair Ahmed',
        actorRole: 'Employee',
        action: 'Submitted claim',
        from: null,
        to: 'Pending',
      },
    ],
    createdAt: '2025-10-04T07:40:00Z',
    priority: 'Normal',
  },
];

// ---- LABS (from labs.json — first 32) ----
interface LabData {
  id: string;
  name: string;
  address: string;
  city: string;
  contact: string;
  type: string;
}

const labs: LabData[] = [
  {
    id: 'lab-001',
    name: 'Burhani Hospital',
    address: 'Gari Khata, Karachi',
    city: 'Karachi',
    contact: '021-32631556',
    type: 'Laboratory',
  },
  {
    id: 'lab-002',
    name: 'Chughtai Laboratory',
    address: 'Al-Khalij Tower Main Shaheed-e-Millat Road, Karachi',
    city: 'Karachi',
    contact: '03111-456-789',
    type: 'Laboratory',
  },
  {
    id: 'lab-003',
    name: 'Chughtai Laboratory',
    address: 'Shop No. 2, Rafiqui Shaheed Road, Karachi',
    city: 'Karachi',
    contact: '03111-456-789',
    type: 'Laboratory',
  },
  {
    id: 'lab-004',
    name: 'Chughtai Laboratory',
    address: 'Shop #04, DHA Phase 7, Karachi',
    city: 'Karachi',
    contact: '03111-456-789',
    type: 'Laboratory',
  },
  {
    id: 'lab-005',
    name: 'Chughtai Laboratory',
    address: 'Clifton Block 07, Karachi',
    city: 'Karachi',
    contact: '03111-456-789',
    type: 'Laboratory',
  },
  {
    id: 'lab-006',
    name: 'Chughtai Laboratory',
    address: 'Gulistan-e-Johar Block 13, Karachi',
    city: 'Karachi',
    contact: '03111-456-789',
    type: 'Laboratory',
  },
  {
    id: 'lab-007',
    name: 'Chughtai Laboratory',
    address: 'Gulshan-e-Iqbal, Karachi',
    city: 'Karachi',
    contact: '03111-456-789',
    type: 'Laboratory',
  },
  {
    id: 'lab-008',
    name: 'Chughtai Laboratory',
    address: 'North Nazimabad, Karachi',
    city: 'Karachi',
    contact: '03111-456-789',
    type: 'Laboratory',
  },
  {
    id: 'lab-009',
    name: 'Chughtai Laboratory',
    address: 'Nazimabad, Karachi',
    city: 'Karachi',
    contact: '03111-456-789',
    type: 'Laboratory',
  },
  {
    id: 'lab-010',
    name: 'Chughtai Laboratory',
    address: 'PECHS Block 2, Karachi',
    city: 'Karachi',
    contact: '03111-456-789',
    type: 'Laboratory',
  },
  {
    id: 'lab-011',
    name: 'Chughtai Laboratory',
    address: 'Tariq Road, Karachi',
    city: 'Karachi',
    contact: '03111-456-789',
    type: 'Laboratory',
  },
  {
    id: 'lab-012',
    name: 'Al-Sehat Center',
    address: 'Bahadurabad, Karachi',
    city: 'Karachi',
    contact: '03111-456-789',
    type: 'Laboratory',
  },
  {
    id: 'lab-013',
    name: 'Chughtai Laboratory',
    address: 'FB Area, Karachi',
    city: 'Karachi',
    contact: '03111-456-789',
    type: 'Laboratory',
  },
  {
    id: 'lab-014',
    name: 'Chughtai Laboratory',
    address: 'Malir, Karachi',
    city: 'Karachi',
    contact: '03111-456-789',
    type: 'Laboratory',
  },
  {
    id: 'lab-015',
    name: 'Chughtai Laboratory',
    address: 'Korangi, Karachi',
    city: 'Karachi',
    contact: '03111-456-789',
    type: 'Laboratory',
  },
  {
    id: 'lab-016',
    name: 'Chughtai Laboratory',
    address: 'Orangi Town, Karachi',
    city: 'Karachi',
    contact: '03111-456-789',
    type: 'Laboratory',
  },
  {
    id: 'lab-017',
    name: 'Chughtai Laboratory - Homecare',
    address: 'Karachi',
    city: 'Karachi',
    contact: '03111-456-789',
    type: 'Home Care',
  },
  {
    id: 'lab-018',
    name: 'Chughtai Laboratory - Homecare Injection',
    address: 'Karachi',
    city: 'Karachi',
    contact: '03111-456-789',
    type: 'Home Care',
  },
  {
    id: 'lab-019',
    name: 'Chughtai Laboratory',
    address: 'Karachi',
    city: 'Karachi',
    contact: '03111-456-789',
    type: 'Home Care',
  },
  {
    id: 'lab-020',
    name: 'Chughtai Laboratory - KHE CC',
    address: 'Karachi',
    city: 'Karachi',
    contact: '03111-456-789',
    type: 'Laboratory',
  },
  {
    id: 'lab-021',
    name: 'Chughtai Laboratory',
    address: 'Saddar, Karachi',
    city: 'Karachi',
    contact: '03111-456-789',
    type: 'Laboratory',
  },
  {
    id: 'lab-022',
    name: 'Chughtai Laboratory',
    address: 'Defence, Karachi',
    city: 'Karachi',
    contact: '03111-456-789',
    type: 'Laboratory',
  },
  {
    id: 'lab-023',
    name: 'Aga Khan Laboratory',
    address: 'Stadium Road, Karachi',
    city: 'Karachi',
    contact: '+92-21-34930000',
    type: 'Laboratory',
  },
  {
    id: 'lab-024',
    name: 'Shifa Laboratory',
    address: 'Pitras Bukhari Road, Islamabad',
    city: 'Islamabad',
    contact: '+92-51-8464646',
    type: 'Laboratory',
  },
  {
    id: 'lab-025',
    name: 'Fatimid Laboratory',
    address: 'Sector G, Islamabad',
    city: 'Islamabad',
    contact: '+92-51-2212004',
    type: 'Laboratory',
  },
  {
    id: 'lab-026',
    name: 'Labs Direct',
    address: 'Gulberg, Lahore',
    city: 'Lahore',
    contact: '+92-42-99213350',
    type: 'Laboratory',
  },
  {
    id: 'lab-027',
    name: 'Shaukat Khanum Lab',
    address: 'Johar Town, Lahore',
    city: 'Lahore',
    contact: '+92-42-35944951',
    type: 'Laboratory',
  },
  {
    id: 'lab-028',
    name: 'Chughtai Laboratory',
    address: 'Model Town, Lahore',
    city: 'Lahore',
    contact: '+92-42-35752220',
    type: 'Laboratory',
  },
  {
    id: 'lab-029',
    name: 'Chughtai Laboratory',
    address: 'DHA, Lahore',
    city: 'Lahore',
    contact: '+92-42-35752220',
    type: 'Laboratory',
  },
  {
    id: 'lab-030',
    name: 'Chughtai Laboratory',
    address: 'Mall Road, Lahore',
    city: 'Lahore',
    contact: '+92-42-99203000',
    type: 'Laboratory',
  },
  {
    id: 'lab-031',
    name: 'AKU Diagnostic Lab',
    address: 'Satellite Town, Rawalpindi',
    city: 'Rawalpindi',
    contact: '+92-51-9290801',
    type: 'Laboratory',
  },
  {
    id: 'lab-032',
    name: 'Shifa Lab',
    address: 'H-8, Islamabad',
    city: 'Islamabad',
    contact: '+92-51-8464646',
    type: 'Laboratory',
  },
];

// ---- DEPENDENTS (from dependents.json) ----
interface DependentData {
  id: string;
  employeeId: string;
  firstName: string;
  lastName: string;
  relationship: 'Spouse' | 'Son' | 'Daughter' | 'Father' | 'Mother';
  dob: string;
  gender: 'Male' | 'Female';
  cnic?: string;
  phone?: string;
  status: 'Pending' | 'Approved' | 'Rejected' | 'Active' | 'Inactive';
  requestDate: string;
  reviewedDate?: string;
}

const dependents: DependentData[] = [
  {
    id: 'dep-001',
    employeeId: 'emp-001',
    firstName: 'Sarah',
    lastName: 'Raza',
    relationship: 'Spouse',
    dob: '1995-03-15',
    gender: 'Female',
    cnic: '42101-1234567-8',
    phone: '+92-300-1234567',
    status: 'Approved',
    requestDate: '2025-01-01T10:00:00Z',
    reviewedDate: '2025-01-02T14:30:00Z',
  },
  {
    id: 'dep-002',
    employeeId: 'emp-001',
    firstName: 'Usman',
    lastName: 'Ali',
    relationship: 'Son',
    dob: '2017-05-20',
    gender: 'Male',
    cnic: '42101-7654321-2',
    status: 'Approved',
    requestDate: '2025-01-01T10:00:00Z',
    reviewedDate: '2025-01-02T14:30:00Z',
  },
  {
    id: 'dep-003',
    employeeId: 'emp-001',
    firstName: 'Ahmed',
    lastName: 'Raza',
    relationship: 'Son',
    dob: '2020-08-10',
    gender: 'Male',
    status: 'Pending',
    requestDate: '2025-11-01T10:30:00Z',
  },
];

// ---- EMERGENCY CONTACTS (from hospitalEmergencyContacts.json — for hosp-001) ----
interface EmergencyContactData {
  level: number;
  designation: string;
  name: string;
  contactNumber: string;
}

const emergencyContacts: EmergencyContactData[] = [
  {
    level: 1,
    designation: 'Head of Insurance',
    name: 'Mr. Ahmed Raza',
    contactNumber: '+92 300 1234567',
  },
  {
    level: 2,
    designation: 'Regional Manager',
    name: 'Ms. Fatima Khan',
    contactNumber: '+92 321 7654321',
  },
  {
    level: 3,
    designation: 'Claims Officer',
    name: 'Mr. Bilal Hussain',
    contactNumber: '+92 333 1112223',
  },
  {
    level: 4,
    designation: 'Claims Assistant',
    name: 'Ms. Sara Malik',
    contactNumber: '+92 334 9998887',
  },
];

// ---- NOTIFICATION DATA ----
interface NotificationData {
  id: string;
  title: string;
  message: string;
  severity: 'info' | 'warning' | 'critical';
  category: string;
  timestamp: string;
  isRead: boolean;
  notificationType:
    | 'claim_status'
    | 'policy_update'
    | 'dependent_request'
    | 'messaging_alert';
}

const insurerNotifications: NotificationData[] = [
  {
    id: 'ins-notif-001',
    title: 'High-Value Claim Flagged',
    message: 'Claim CLM-2025-0001 for Rs. 125,000 has been flagged for review.',
    severity: 'critical',
    category: 'claims',
    timestamp: '2025-10-04T09:00:00Z',
    isRead: false,
    notificationType: 'claim_status',
  },
  {
    id: 'ins-notif-002',
    title: 'Policy Renewal Pending',
    message:
      'Corporate plan for Beta Systems (plan-beta-silver-2025) expires in 30 days.',
    severity: 'warning',
    category: 'policies',
    timestamp: '2025-10-03T14:00:00Z',
    isRead: false,
    notificationType: 'policy_update',
  },
  {
    id: 'ins-notif-003',
    title: 'Dependent Verification Delay',
    message: 'Dependent request (dep-003) for Ahmed Raza pending for 5+ days.',
    severity: 'info',
    category: 'dependents',
    timestamp: '2025-10-02T10:00:00Z',
    isRead: true,
    notificationType: 'dependent_request',
  },
  {
    id: 'ins-notif-004',
    title: 'Unread Message',
    message:
      'You have an unread message from Imran Qureshi on claim CLM-2025-0008.',
    severity: 'info',
    category: 'messaging',
    timestamp: '2025-10-01T16:00:00Z',
    isRead: false,
    notificationType: 'messaging_alert',
  },
];

const hospitalNotifications: NotificationData[] = [
  {
    id: 'hosp-notif-001',
    title: 'High-Value Claim Submitted',
    message:
      'A claim for Rs. 125,000 (CLM-2025-0001) was submitted. Review required.',
    severity: 'critical',
    category: 'claims',
    timestamp: '2025-10-04T09:30:00Z',
    isRead: false,
    notificationType: 'claim_status',
  },
  {
    id: 'hosp-notif-002',
    title: 'Policy Near Expiry',
    message: 'Acme Ltd corporate contract expires on 2025-12-31.',
    severity: 'warning',
    category: 'policies',
    timestamp: '2025-10-03T11:00:00Z',
    isRead: false,
    notificationType: 'policy_update',
  },
  {
    id: 'hosp-notif-003',
    title: 'Pending Dependent Requests',
    message: '1 dependent request awaiting your verification.',
    severity: 'info',
    category: 'dependents',
    timestamp: '2025-10-02T08:00:00Z',
    isRead: true,
    notificationType: 'dependent_request',
  },
  {
    id: 'hosp-notif-004',
    title: 'Unread Message',
    message: 'New message from insurer on claim CLM-2025-0004.',
    severity: 'info',
    category: 'messaging',
    timestamp: '2025-10-01T15:00:00Z',
    isRead: false,
    notificationType: 'messaging_alert',
  },
];

const patientNotifications: NotificationData[] = [
  {
    id: 'pat-notif-001',
    title: 'Claim Update',
    message:
      'Your claim CLM-2025-0001 status has been reviewed by the insurer.',
    severity: 'warning',
    category: 'claims',
    timestamp: '2025-10-04T10:00:00Z',
    isRead: false,
    notificationType: 'claim_status',
  },
  {
    id: 'pat-notif-002',
    title: 'Benefit Reminder',
    message: 'You have used 60% of your OPD coverage for 2025.',
    severity: 'info',
    category: 'benefits',
    timestamp: '2025-10-03T09:00:00Z',
    isRead: true,
    notificationType: 'policy_update',
  },
  {
    id: 'pat-notif-003',
    title: 'Coverage Threshold',
    message: 'Your coverage usage has crossed 75%. Consider contacting HR.',
    severity: 'critical',
    category: 'coverage',
    timestamp: '2025-10-02T14:00:00Z',
    isRead: false,
    notificationType: 'policy_update',
  },
  {
    id: 'pat-notif-004',
    title: 'Policy Renewed',
    message: 'Your insurance plan has been renewed until 2025-12-31.',
    severity: 'info',
    category: 'policies',
    timestamp: '2025-10-01T08:00:00Z',
    isRead: true,
    notificationType: 'policy_update',
  },
];

const corporateNotifications: NotificationData[] = [
  {
    id: 'corp-notif-001',
    title: 'High Claim Spend Alert',
    message: 'Your corporate claim spend has exceeded Rs. 200,000 this month.',
    severity: 'critical',
    category: 'claims',
    timestamp: '2025-10-04T11:00:00Z',
    isRead: false,
    notificationType: 'claim_status',
  },
  {
    id: 'corp-notif-002',
    title: 'Plan Renewal Reminder',
    message:
      'Your plan-acme-gold-2025 is expiring on 2025-12-31. Contact insurer.',
    severity: 'warning',
    category: 'policies',
    timestamp: '2025-10-03T10:00:00Z',
    isRead: false,
    notificationType: 'policy_update',
  },
  {
    id: 'corp-notif-003',
    title: 'Pending Dependent Approvals',
    message: '1 dependent request from Ali Raza is pending approval.',
    severity: 'info',
    category: 'dependents',
    timestamp: '2025-10-02T09:00:00Z',
    isRead: true,
    notificationType: 'dependent_request',
  },
  {
    id: 'corp-notif-004',
    title: 'Quarterly Audit Pending',
    message: 'Review 3rd quarter compliance audit by end of month.',
    severity: 'info',
    category: 'compliance',
    timestamp: '2025-10-01T07:00:00Z',
    isRead: false,
    notificationType: 'policy_update',
  },
];

// ---------------------------------------------------------------------------
// HELPER
// ---------------------------------------------------------------------------
function splitName(fullName: string): { first: string; last: string | null } {
  const parts = fullName.trim().split(/\s+/);
  if (parts.length === 1) return { first: parts[0], last: null };
  return { first: parts[0], last: parts.slice(1).join(' ') };
}

function mapGender(g?: string): 'Male' | 'Female' | 'Other' {
  if (g === 'Male') return 'Male';
  if (g === 'Female') return 'Female';
  return 'Other';
}

function mapClaimStatus(
  s: string,
): 'Pending' | 'Approved' | 'Rejected' | 'Paid' | 'OnHold' {
  if (s === 'Approved') return 'Approved';
  if (s === 'Rejected') return 'Rejected';
  return 'Pending';
}

function mapClaimEventStatus(
  s: string | null,
): 'Pending' | 'Approved' | 'Rejected' | 'Paid' | 'OnHold' {
  if (s === 'Approved') return 'Approved';
  if (s === 'Rejected') return 'Rejected';
  if (s === 'Paid') return 'Paid';
  if (s === 'OnHold') return 'OnHold';
  return 'Pending';
}

// ---------------------------------------------------------------------------
// MAIN SEED FUNCTION
// ---------------------------------------------------------------------------
async function main() {
  console.log('🌱 Starting InsureLink database seed...\n');

  // Hash the password once
  const passwordHash = await bcrypt.hash('password123', 10);

  // ========================================================================
  // STEP 0: Clean existing data (reverse dependency order)
  // ========================================================================
  console.log('🗑️  Cleaning existing data...');
  await prisma.notification.deleteMany();
  await prisma.claimEvent.deleteMany();
  await prisma.claimDocument.deleteMany();
  await prisma.chatMessageAttachment.deleteMany();
  await prisma.chatMessage.deleteMany();
  await prisma.claim.deleteMany();
  await prisma.hospitalVisit.deleteMany();
  await prisma.dependent.deleteMany();
  await prisma.employee.deleteMany();
  await prisma.lab.deleteMany();
  await prisma.plan.deleteMany();
  await prisma.hospitalEmergencyContact.deleteMany();
  await prisma.hospital.deleteMany();
  await prisma.corporate.deleteMany();
  await prisma.insurer.deleteMany();
  await prisma.auditLog.deleteMany();
  await prisma.user.deleteMany();
  console.log('   ✅ All tables cleared\n');

  // ========================================================================
  // STEP 1: Create Insurer User + Insurer
  // ========================================================================
  console.log('🏢 Creating Insurer...');
  const insurerUser = await prisma.user.create({
    data: {
      email: 'admin@insurelink.com',
      passwordHash,
      firstName: 'InsureLink',
      lastName: 'Admin',
      phone: '+92-21-1234567',
      userRole: 'insurer',
      address: 'Karachi, Pakistan',
    },
  });
  createdIds.insurerUser = insurerUser.id;

  const insurer = await prisma.insurer.create({
    data: {
      userId: insurerUser.id,
      companyName: 'HealthGuard Insurance',
      licenseNumber: 'INS-2020-8901',
      address: 'I.I. Chundrigar Road, Karachi',
      city: 'Karachi',
      province: 'Sindh',
      maxCoverageLimit: 5000000,
      networkHospitalCount: 12,
      corporateClientCount: 3,
      status: 'Active',
      operatingSince: new Date('2020-01-01'),
      isActive: true,
    },
  });
  createdIds.insurer = insurer.id;
  ID_MAP['insurer'] = insurer.id;
  console.log('   ✅ Insurer created: HealthGuard Insurance\n');

  // ========================================================================
  // STEP 2: Create Hospital Users + Hospitals
  // ========================================================================
  console.log('🏥 Creating Hospitals...');
  for (let i = 0; i < hospitals.length; i++) {
    const h = hospitals[i];
    const idx = i + 1;
    const email = `hospital${String(idx).padStart(3, '0')}@insurelink.com`;
    const { first, last } = splitName(h.name);

    // Create user for hospital
    const hospUser = await prisma.user.create({
      data: {
        email,
        passwordHash,
        firstName: first,
        lastName: last,
        phone: h.contact,
        userRole: 'hospital',
        address: h.address,
      },
    });
    createdIds.hospUsers.push(hospUser.id);

    // Create hospital
    const hospital = await prisma.hospital.create({
      data: {
        userId: hospUser.id,
        hospitalName: h.name,
        licenseNumber: `HOSP-LIC-${String(idx).padStart(3, '0')}`,
        city: h.city,
        address: h.address,
        latitude: h.lat ?? null,
        longitude: h.lng ?? null,
        emergencyPhone: h.contact,
        hospitalType: h.type as 'reimbursable' | 'non_reimbursable',
        hasEmergencyUnit: h.hasEmergency ?? h.type === 'reimbursable',
        isActive: true,
      },
    });
    createdIds.hosps.push(hospital.id);
    ID_MAP[h.id] = hospital.id;
  }
  console.log(`   ✅ ${hospitals.length} hospitals created\n`);

  // ========================================================================
  // STEP 3: Create Corporate Users + Corporates
  // ========================================================================
  console.log('🏬 Creating Corporates...');
  const corporateData = [
    {
      frontendId: 'corp-001',
      name: 'Acme Ltd',
      email: 'sara.ahmed@acme.com',
      phone: '+92-300-1111111',
      contactName: 'Sara Ahmed',
      city: 'Islamabad',
      province: 'ICT',
      empCount: 8,
      contractStart: '2025-01-01',
      contractEnd: '2025-12-31',
    },
    {
      frontendId: 'corp-002',
      name: 'Beta Systems',
      email: 'imran.shah@beta.com',
      phone: '+92-300-2222222',
      contactName: 'Imran Shah',
      city: 'Lahore',
      province: 'Punjab',
      empCount: 7,
      contractStart: '2025-01-01',
      contractEnd: '2025-12-31',
    },
    {
      frontendId: 'corp-003',
      name: 'Noor Foods',
      email: 'fatima.noor@noorfoods.com',
      phone: '+92-300-3333333',
      contactName: 'Fatima Noor',
      city: 'Karachi',
      province: 'Sindh',
      empCount: 5,
      contractStart: '2025-02-01',
      contractEnd: '2026-01-31',
    },
  ];

  for (const c of corporateData) {
    const corpUser = await prisma.user.create({
      data: {
        email: c.email,
        passwordHash,
        firstName: c.contactName.split(' ')[0],
        lastName: c.contactName.split(' ').slice(1).join(' ') || null,
        phone: c.phone,
        userRole: 'corporate',
        address: `${c.city}, ${c.province}`,
      },
    });
    createdIds.corpUsers.push(corpUser.id);

    const corporate = await prisma.corporate.create({
      data: {
        userId: corpUser.id,
        name: c.name,
        address: `${c.city} Office`,
        city: c.city,
        province: c.province,
        employeeCount: c.empCount,
        dependentCount: c.name === 'Acme Ltd' ? 3 : 0,
        insurerId: insurer.id,
        contactName: c.contactName,
        contactEmail: c.email,
        contactPhone: c.phone,
        contractStartDate: new Date(c.contractStart),
        contractEndDate: new Date(c.contractEnd),
        totalAmountUsed: 0,
        status: 'Active',
      },
    });
    createdIds.corps.push(corporate.id);
    ID_MAP[c.frontendId] = corporate.id;
  }
  console.log(`   ✅ ${corporateData.length} corporates created\n`);

  // ========================================================================
  // STEP 4: Create Plans
  // ========================================================================
  console.log('📋 Creating Plans...');
  for (const p of plans) {
    const plan = await prisma.plan.create({
      data: {
        planName: p.name,
        planCode: p.planCode,
        insurerId: insurer.id,
        sumInsured: p.sumInsured,
        coveredServices: p.coveredServices,
        serviceLimits: p.limits,
        isActive: true,
      },
    });
    createdIds.plans.push(plan.id);
    ID_MAP[p.id] = plan.id;
  }
  console.log(`   ✅ ${plans.length} plans created\n`);

  // ========================================================================
  // STEP 5: Create Employee Users + Employees
  // ========================================================================
  console.log('👤 Creating Employees (Patient users)...');
  for (let i = 0; i < employees.length; i++) {
    const e = employees[i];
    const { first, last } = splitName(e.name);

    const empUser = await prisma.user.create({
      data: {
        email: e.email,
        passwordHash,
        firstName: first,
        lastName: last,
        phone: e.mobile,
        userRole: 'patient',
        dob: e.dob ? new Date(e.dob) : null,
        gender: e.gender ? mapGender(e.gender) : null,
        cnic: e.cnic?.replace(/-/g, '') || null, // Remove dashes from CNIC
        address: e.address || null,
      },
    });
    createdIds.empUsers.push(empUser.id);

    const employee = await prisma.employee.create({
      data: {
        userId: empUser.id,
        corporateId: ID_MAP[e.corporateId],
        employeeNumber: e.employeeNumber,
        planId: ID_MAP[e.planId],
        designation: e.designation,
        department: e.department,
        coverageStartDate: new Date(e.coverageStart),
        coverageEndDate: new Date(e.coverageEnd),
        coverageAmount:
          plans.find((p) => p.id === e.planId)?.sumInsured ?? 500000,
        usedAmount: 0,
        status: 'Active',
      },
    });
    createdIds.emps.push(employee.id);
    ID_MAP[e.id] = employee.id;
  }
  console.log(`   ✅ ${employees.length} employees created\n`);

  // ========================================================================
  // STEP 6: Create Dependents
  // ========================================================================
  console.log('👨‍👩‍👧 Creating Dependents...');
  for (const d of dependents) {
    const dependent = await prisma.dependent.create({
      data: {
        employeeId: ID_MAP[d.employeeId],
        firstName: d.firstName,
        lastName: d.lastName,
        relationship: d.relationship,
        dateOfBirth: new Date(d.dob),
        gender: d.gender,
        cnic: d.cnic?.replace(/-/g, '') || null,
        phoneNumber: d.phone || null,
        status: d.status as 'Pending' | 'Approved',
        requestDate: new Date(d.requestDate),
        reviewedDate: d.reviewedDate ? new Date(d.reviewedDate) : null,
      },
    });
    createdIds.deps.push(dependent.id);
    ID_MAP[d.id] = dependent.id;
  }
  console.log(`   ✅ ${dependents.length} dependents created\n`);

  // ========================================================================
  // STEP 7: Create Hospital Visits (one per claim, derived from claims data)
  // ========================================================================
  console.log('🏨 Creating Hospital Visits...');
  // Map claim IDs to visit IDs
  const claimVisitMap: Record<string, string> = {};

  for (const c of claims) {
    const visit = await prisma.hospitalVisit.create({
      data: {
        employeeId: ID_MAP[c.employeeId],
        dependentId: null,
        hospitalId: ID_MAP[c.hospitalId],
        visitDate: new Date(c.admissionDate),
        dischargeDate: new Date(c.dischargeDate),
      },
    });
    createdIds.visits.push(visit.id);
    claimVisitMap[c.id] = visit.id;
  }
  console.log(`   ✅ ${claims.length} hospital visits created\n`);

  // ========================================================================
  // STEP 8: Create Claims
  // ========================================================================
  console.log('📄 Creating Claims...');
  const createdClaimsMap: Record<string, string> = {};

  for (const c of claims) {
    const claim = await prisma.claim.create({
      data: {
        claimNumber: c.claimNumber,
        hospitalVisitId: claimVisitMap[c.id],
        corporateId: ID_MAP[c.corporateId],
        planId: ID_MAP[c.planId],
        insurerId: insurer.id,
        claimStatus: mapClaimStatus(c.status),
        amountClaimed: c.amountClaimed,
        approvedAmount: c.approvedAmount,
        treatmentCategory: c.treatmentCategory,
        priority: c.priority,
        notes: null,
      },
    });
    createdIds.claims.push(claim.id);
    createdClaimsMap[c.id] = claim.id;
    ID_MAP[c.id] = claim.id;

    // Update employee used amount
    if (c.approvedAmount > 0) {
      await prisma.employee.update({
        where: { id: ID_MAP[c.employeeId] },
        data: { usedAmount: { increment: c.approvedAmount } },
      });
    }
  }

  // Update corporate total_amount_used
  const totalUsed: Record<string, number> = {};
  for (const c of claims) {
    if (c.approvedAmount > 0) {
      totalUsed[c.corporateId] =
        (totalUsed[c.corporateId] || 0) + c.approvedAmount;
    }
  }
  for (const [corpId, amount] of Object.entries(totalUsed)) {
    await prisma.corporate.update({
      where: { id: ID_MAP[corpId] },
      data: { totalAmountUsed: amount },
    });
  }
  console.log(`   ✅ ${claims.length} claims created\n`);

  // ========================================================================
  // STEP 9: Create Claim Events
  // ========================================================================
  console.log('📝 Creating Claim Events...');
  let eventCount = 0;
  for (const c of claims) {
    for (const ev of c.events) {
      await prisma.claimEvent.create({
        data: {
          claimId: createdClaimsMap[c.id],
          actorName: ev.actorName,
          actorRole: ev.actorRole,
          action: ev.action,
          statusFrom: ev.from ? mapClaimEventStatus(ev.from) : undefined,
          statusTo: mapClaimEventStatus(ev.to),
          eventNote: ev.note ?? undefined,
          timestamp: new Date(ev.ts),
          createdAt: new Date(ev.ts),
        },
      });
      eventCount++;
    }
  }
  console.log(`   ✅ ${eventCount} claim events created\n`);

  // ========================================================================
  // STEP 10: Create Hospital Emergency Contacts (for hosp-001)
  // ========================================================================
  console.log('📞 Creating Emergency Contacts...');
  for (const ec of emergencyContacts) {
    const contact = await prisma.hospitalEmergencyContact.create({
      data: {
        hospitalId: createdIds.hosps[0], // First hospital (hosp-001)
        contactLevel: ec.level,
        designation: ec.designation,
        name: ec.name,
        contactNumber: ec.contactNumber,
        isActive: true,
      },
    });
    createdIds.emergContacts.push(contact.id);
  }
  console.log(`   ✅ ${emergencyContacts.length} emergency contacts created\n`);

  // ========================================================================
  // STEP 11: Create Labs
  // ========================================================================
  console.log('🔬 Creating Labs...');
  for (let i = 0; i < labs.length; i++) {
    const l = labs[i];
    const idx = i + 1;
    const lab = await prisma.lab.create({
      data: {
        insurerId: insurer.id,
        labName: l.name,
        city: l.city,
        address: l.address,
        licenseNumber: `LAB-LIC-${String(idx).padStart(3, '0')}`,
        contactPhone: l.contact,
        contactEmail: `lab${String(idx).padStart(3, '0')}@insurelink.com`,
        testCategories:
          l.type === 'Home Care'
            ? ['Blood Tests', 'Injections', 'Home Collection']
            : [
                'Blood Tests',
                'Urine Analysis',
                'X-Ray',
                'Ultrasound',
                'CT Scan',
              ],
        isActive: true,
      },
    });
    createdIds.labs.push(lab.id);
    ID_MAP[l.id] = lab.id;
  }
  console.log(`   ✅ ${labs.length} labs created\n`);

  // ========================================================================
  // STEP 12: Create Notifications
  // ========================================================================
  console.log('🔔 Creating Notifications...');
  let notifCount = 0;

  // Insurer notifications (for the insurer user)
  for (const n of insurerNotifications) {
    const notif = await prisma.notification.create({
      data: {
        userId: createdIds.insurerUser,
        notificationType: n.notificationType,
        title: n.title,
        message: n.message,
        severity: n.severity,
        isRead: n.isRead,
        timestamp: new Date(n.timestamp),
      },
    });
    createdIds.notifications.push(notif.id);
    notifCount++;
  }

  // Hospital notifications (for hosp-001 user)
  for (const n of hospitalNotifications) {
    const notif = await prisma.notification.create({
      data: {
        userId: createdIds.hospUsers[0],
        notificationType: n.notificationType,
        title: n.title,
        message: n.message,
        severity: n.severity,
        isRead: n.isRead,
        timestamp: new Date(n.timestamp),
      },
    });
    createdIds.notifications.push(notif.id);
    notifCount++;
  }

  // Patient notifications (for emp-001 / Ali Raza)
  for (const n of patientNotifications) {
    const notif = await prisma.notification.create({
      data: {
        userId: createdIds.empUsers[0],
        notificationType: n.notificationType,
        title: n.title,
        message: n.message,
        severity: n.severity,
        isRead: n.isRead,
        timestamp: new Date(n.timestamp),
      },
    });
    createdIds.notifications.push(notif.id);
    notifCount++;
  }

  // Corporate notifications (for corp-001 user / Sara Ahmed)
  for (const n of corporateNotifications) {
    const notif = await prisma.notification.create({
      data: {
        userId: createdIds.corpUsers[0],
        notificationType: n.notificationType,
        title: n.title,
        message: n.message,
        severity: n.severity,
        isRead: n.isRead,
        timestamp: new Date(n.timestamp),
      },
    });
    createdIds.notifications.push(notif.id);
    notifCount++;
  }
  console.log(`   ✅ ${notifCount} notifications created\n`);

  // ========================================================================
  // SUMMARY
  // ========================================================================
  console.log('═══════════════════════════════════════════════════════════');
  console.log('✅ SEED COMPLETE! Database populated with:');
  console.log('───────────────────────────────────────────────────────────');
  console.log(
    `  Users:               ${1 + hospitals.length + corporateData.length + employees.length}`,
  );
  console.log(`  Insurer:             1 (HealthGuard Insurance)`);
  console.log(`  Hospitals:           ${hospitals.length}`);
  console.log(`  Corporates:          ${corporateData.length}`);
  console.log(`  Plans:               ${plans.length}`);
  console.log(`  Employees:           ${employees.length}`);
  console.log(`  Dependents:          ${dependents.length}`);
  console.log(`  Hospital Visits:     ${claims.length}`);
  console.log(`  Claims:              ${claims.length}`);
  console.log(`  Claim Events:        ${eventCount}`);
  console.log(`  Emergency Contacts:  ${emergencyContacts.length}`);
  console.log(`  Labs:                ${labs.length}`);
  console.log(`  Notifications:       ${notifCount}`);
  console.log('───────────────────────────────────────────────────────────');
  console.log('');
  console.log('🔑 LOGIN CREDENTIALS:');
  console.log('  All users: password123');
  console.log('');
  console.log('  Insurer:    admin@insurelink.com');
  console.log('  Corp (Acme): sara.ahmed@acme.com');
  console.log('  Corp (Beta): imran.shah@beta.com');
  console.log('  Corp (Noor): fatima.noor@noorfoods.com');
  console.log('  Hospital 1:  hospital001@insurelink.com');
  console.log('  Patient 1:   ali.raza@acme.com');
  console.log('═══════════════════════════════════════════════════════════');
}

// ---------------------------------------------------------------------------
// RUN
// ---------------------------------------------------------------------------
main()
  .then(async () => {
    await prisma.$disconnect();
    process.exit(0);
  })
  .catch(async (e) => {
    console.error('❌ Seed failed:', e);
    await prisma.$disconnect();
    process.exit(1);
  });
